import fs from "node:fs/promises";
import process from "node:process";

import { builtinRules } from "eslint/use-at-your-own-risk";
import { flatConfigsToRulesDTS } from "eslint-typegen/core";

import { fastConfig } from "../src/code";

import type { ESLint, Linter } from "eslint";

const outputUrl = new URL("../src/typegen.d.ts", import.meta.url);
const checkOnly = process.argv.includes("--check");

const corePlugin: ESLint.Plugin = {
	rules: Object.fromEntries(builtinRules.entries()),
};

const configs: Linter.Config[] = [
	{
		name: "@fast-china/typegen/core",
		plugins: {
			"": corePlugin,
		},
	},
	...fastConfig({ angular: true, gitignore: false, react: true }),
];

const declarations = await flatConfigsToRulesDTS(configs, {
	exportTypeName: "RuleOptions",
	includeAugmentation: false,
	includeIgnoreComments: true,
	includeTypeImports: true,
});
const normalizedDeclarations = declarations.replace(/[\t ]+$/gm, "").trimEnd();

const generated = `/**
 * Generated from the rule schemas of ESLint and every plugin shipped by this package.
 * Run \`pnpm run typegen\` after changing plugin versions; do not edit this file manually.
 */
${normalizedDeclarations}
`;

if (checkOnly) {
	const current = await fs.readFile(outputUrl, "utf8").catch(() => "");

	if (current !== generated) {
		console.error("Generated rule types are stale. Run `pnpm run typegen` and commit src/typegen.d.ts.");
		process.exitCode = 1;
	}
} else {
	await fs.writeFile(outputUrl, generated, "utf8");
	console.log("Generated src/typegen.d.ts.");
}
